import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {randomBytes,timingSafeEqual,createHmac} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {isolatedPreview} from './preview.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));
const attempts=new Map(),queue=[];let snapshot=null,lastSeen=0;
const commandResults=new Map();
const secret=process.env.FORGERADAR_BRIDGE_TOKEN,password=process.env.FORGERADAR_ADMIN_PASSWORD;
if(!secret||secret.length<32||!password||password.length<16)throw new Error('Configure the bridge token and admin password before starting the public service.');
const equal=(a,b)=>{const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&timingSafeEqual(x,y);};
const login=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ForgeRadar · Sign in</title><script src="/login.js" defer></script><link rel="stylesheet" href="/style.css"></head><body class="auth-page"><main class="panel auth-panel"><span class="tag">FORGERADAR / OWNER ACCESS</span><h1>Your agent workshop.</h1><p>Sign in to inspect the circuit and send work to your local agents.</p><form method="post" action="/login"><label for="password">Workshop password</label><input id="password" name="password" type="password" autocomplete="current-password" required><button type="submit">Enter workshop</button></form><p id="loginNotice" role="status" aria-live="polite"></p><p class="muted">Your agents run on your laptop. Your projects stay private.</p></main></body></html>`;
export const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');const json=(code,body)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(body));};try{
res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; frame-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'none'");
if(url.pathname==='/health')return json(200,{service:'ForgeRadar',workerOnline:Date.now()-lastSeen<45000});
let raw='';if(req.method==='POST'){for await(const c of req){raw+=c;if(Buffer.byteLength(raw)>4000000)return json(413,{error:'Request too large'});}}
if(url.pathname==='/bridge'&&req.method==='POST'){if(!equal(req.headers.authorization,'Bearer '+secret))return json(401,{error:'Unauthorized worker'});const body=JSON.parse(raw);if(!body.state||!body.machine||!body.models)return json(400,{error:'Incomplete worker snapshot'});snapshot=body;if(body.lastCommandResult){commandResults.set(body.lastCommandResult.id,body.lastCommandResult);if(commandResults.size>500)commandResults.delete(commandResults.keys().next().value);if(!body.lastCommandResult.ok)snapshot.machine.events.unshift({id:body.lastCommandResult.id,at:body.lastCommandResult.at,agent:'bridge',type:'blocked',message:body.lastCommandResult.message});}lastSeen=Date.now();const command=queue[0]||null;if(body.completedId&&command?.id===body.completedId)queue.shift();return json(200,{command:queue[0]||null});}
if(url.pathname==='/login'&&req.method==='POST'){const origin=req.headers.origin;if(origin&&origin!==`https://${req.headers.host}`&&origin!==`http://${req.headers.host}`)return json(403,{error:'Origin rejected'});const ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress).split(',').at(-1).trim();const prior=attempts.get(ip);if(prior&&Date.now()-prior.at<600000&&prior.count>=8)return json(429,{error:'Too many sign-in attempts. Try again in ten minutes.'});if(!equal(new URLSearchParams(raw).get('password'),password)){attempts.set(ip,{at:prior&&Date.now()-prior.at<600000?prior.at:Date.now(),count:prior&&Date.now()-prior.at<600000?prior.count+1:1});return json(401,{error:'Incorrect workshop password'});}attempts.delete(ip);const payload=randomBytes(32).toString('hex')+'.'+(Date.now()+12*3600000).toString(16);const id=payload+'.'+createHmac('sha256',secret+password).update(payload).digest('hex');if(req.headers.accept==='application/json'){res.setHeader('Set-Cookie',`forge_session=${id}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`);return json(200,{ok:true});}res.writeHead(303,{'Location':'/','Set-Cookie':`forge_session=${id}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`});res.end();return;}
const session=req.headers.cookie?.match(/(?:^|; )forge_session=([a-f0-9]{64}\.[a-f0-9]{10,16}\.[a-f0-9]{64})/)?.[1];const pieces=(session||'').split('.');const authorized=pieces.length===3&&parseInt(pieces[1],16)>Date.now()&&equal(pieces[2],createHmac('sha256',secret+password).update(pieces[0]+'.'+pieces[1]).digest('hex'));
if(url.pathname==='/login.js'&&req.method==='GET'){res.setHeader('Content-Type','text/javascript');res.end(await readFile(path.join(root,'public/login.js')));return;}
if(url.pathname==='/style.css'){res.setHeader('Content-Type','text/css');res.end(await readFile(path.join(root,'public/style.css')));return;}
if(!authorized){if(url.pathname.startsWith('/api/')||url.pathname.startsWith('/preview/')||/^\/apps\/[^/]+\/api$/.test(url.pathname))return json(401,{error:'Sign in to the ForgeRadar workshop.'});res.setHeader('Content-Type','text/html; charset=utf-8');res.end(login);return;}
if(url.pathname==='/api/commands'&&req.method==='GET')return json(200,{workerOnline:Date.now()-lastSeen<45000,busy:!!snapshot?.state.busy||snapshot?.machine.machine.status==='running',results:[...queue.filter(c=>c.route==='chat').map(c=>({id:c.body.commandId||c.id,status:'accepted'})),...[...commandResults.values()].filter(c=>!c.ok).map(c=>({id:c.id,status:'failed',error:c.message})),...(snapshot?.state.commandReceipts||[])]});
if(/^\/apps\/[-a-f0-9]{36}\/(?:workspace\.(?:js|css)|api)?$/.test(url.pathname)){const parts=url.pathname.split('/'),id=parts[2];if(!snapshot?.state.projects.some(p=>p.id===id&&p.appSpec))return json(404,{error:'Application unavailable'});if(parts[3]==='api'&&req.method==='POST'){if(req.headers.origin!==`https://${req.headers.host}`&&req.headers.origin!==`http://${req.headers.host}`)return json(403,{error:'Origin rejected'});if(Date.now()-lastSeen>45000)return json(503,{error:'Laptop worker is offline. Your saved data is on its database.'});if(queue.length>30)return json(429,{error:'Worker request queue is full'});const operation=JSON.parse(raw||'{}');const command={id:randomBytes(16).toString('hex'),route:'app',body:{projectId:id,operation}};queue.push(command);const until=Date.now()+25000;while(Date.now()<until){const result=commandResults.get(command.id);if(result)return json(result.ok?200:400,result.ok?result.result:{error:result.message});await new Promise(r=>setTimeout(r,100));}return json(504,{error:'Worker response timed out. Refresh to check whether the operation completed.'});}if(req.method!=='GET'||parts[3]==='api')return json(404,{error:'Not found'});const filename=parts[3]||'workspace.html';res.setHeader('Content-Type',filename.endsWith('.html')?'text/html; charset=utf-8':filename.endsWith('.css')?'text/css':'text/javascript');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; frame-ancestors 'self'; base-uri 'none'; form-action 'self'");res.end(await readFile(path.join(root,'public',filename)));return;}
if(req.method==='GET'&&url.pathname.startsWith('/api/')){const route=url.pathname.slice(5);if(!snapshot)return json(503,{error:'Local worker has not connected. Start ForgeRadar on your laptop.'});const online=Date.now()-lastSeen<45000;if(route==='state')return json(200,{...snapshot.state,workerOnline:online});if(route==='machine')return json(200,{...snapshot.machine,workerOnline:online});if(route==='models')return json(200,online?snapshot.models:{connected:false,models:[]});if(route==='github')return json(200,snapshot.machine.github);if(route==='events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store'});res.write(`event: state\ndata: ${JSON.stringify(snapshot.machine)}\n\n`);const timer=setInterval(()=>{if(snapshot)res.write(`event: state\ndata: ${JSON.stringify({...snapshot.machine,workerOnline:Date.now()-lastSeen<45000})}\n\n`);},3000);req.on('close',()=>clearInterval(timer));return;}return json(404,{error:'Unknown API'});}
if(req.method==='POST'&&url.pathname.startsWith('/api/')){if(req.headers.origin!==`https://${req.headers.host}`&&req.headers.origin!==`http://${req.headers.host}`)return json(403,{error:'Origin rejected'});const route=url.pathname.slice(5),body=JSON.parse(raw||'{}');if(route==='chat'&&body.commandId){if(!/^[-a-zA-Z0-9]{8,100}$/.test(body.commandId)||typeof body.text!=='string'||!body.text.trim()||body.text.length>8000)return json(400,{error:'Invalid instruction'});const prior=snapshot?.state.commandReceipts?.find(r=>r.id===body.commandId);if(prior)return json(200,prior);if(queue.some(c=>c.id===body.commandId))return json(200,{accepted:true,status:'accepted'});}if(Date.now()-lastSeen>45000)return json(503,{error:'Local worker is offline. Instructions remain in your browser queue.'});if(url.pathname!=='/api/cancel'&&(queue.length||snapshot?.state.busy||snapshot?.machine.machine.status==='running'))return json(409,{error:'A command or mission is already running.'});if(!['cancel','chat','mission','automation','import','refresh','analyze','settings','opportunity','project','sample'].includes(route))return json(404,{error:'Unknown action'});queue.push({id:body.commandId||randomBytes(16).toString('hex'),route,body});return json(202,{accepted:true});}
if(req.method==='GET'&&url.pathname.startsWith('/preview/')){const [, ,id,asset]=url.pathname.split('/');const project=snapshot?.previews?.[id];if(!project||!['index.html','style.css','app.js'].includes(asset))return json(404,{error:'Preview unavailable'});res.setHeader('Content-Type',asset.endsWith('.html')?'text/html; charset=utf-8':asset.endsWith('.css')?'text/css':'text/javascript');if(asset==='index.html'){const preview=isolatedPreview(project);res.setHeader('Content-Security-Policy',preview.csp);res.end(preview.html);}else res.end(project[asset]);return;}
const files={'/':'index.html','/app.js':'app.js','/console.js':'console.js','/outbox.js':'outbox.js'};if(req.method!=='GET'||!files[url.pathname])return json(404,{error:'Not found'});res.setHeader('Content-Type',url.pathname==='/'?'text/html; charset=utf-8':'text/javascript');res.end(await readFile(path.join(root,'public',files[url.pathname])));
}catch{json(400,{error:'The request could not be processed.'});}});
if(process.argv[1]===fileURLToPath(import.meta.url))server.listen(Number(process.env.PORT||4318),'0.0.0.0',()=>console.log('ForgeRadar public dashboard ready'));
