import {createHash} from 'node:crypto';
export function decodeEntities(value){return value.replace(/&#(x[\da-f]+|\d+);/gi,(_,n)=>{const v=n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):Number(n);return v>=0&&v<=0x10ffff?String.fromCodePoint(v):'';}).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;|&#39;/g,"'").replace(/&amp;/g,'&');}
export function classifySignal(signal){if(signal.source==='GitHub')return 'Existing project';const body=signal.title+' '+(signal.description||'');if(/\[smt\]|somebody (?:make|build)|someone (?:should|could) (?:make|build)|wish (?:there|i)|app idea|idea for|someone build|does not exist|doesn.t exist|unbuilt|would pay|not yet built|hasn.t been built|need an? (?:app|tool)|looking for an? (?:app|tool)/i.test(body))return 'Idea request';if(/problem|frustrat|pain point|difficult|struggl|annoy/i.test(body))return 'Problem signal';return 'Discussion';}
export function parseRedditFeed(xml){return [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].slice(0,15).map(([,entry])=>{const title=decodeEntities(entry.match(/<title[^>]*>([\s\S]*?)<\/title>/)?.[1]||'');const url=decodeEntities(entry.match(/<link\b[^>]*href="([^"]+)"/)?.[1]||'');const id=entry.match(/<id>([^<]+)<\/id>/)?.[1]||createHash('sha256').update(url).digest('hex');const markup=decodeEntities(entry.match(/<content[^>]*>([\s\S]*?)<\/content>/)?.[1]||'');const description=markup.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,1600);return {id:'reddit-'+id,source:'Reddit',title,url,description,engagement:0,collectedAt:new Date().toISOString()};}).filter(s=>s.title&&s.url.startsWith('https://www.reddit.com/'));}
export async function socialSignals(state){const signals=[],sources=[];
try{const feed='https://www.reddit.com/r/SomebodyMakeThis+AppIdeas+SideProject/.rss';const cache=state.redditCache;let posts;if(cache&&cache.feed===feed&&Date.now()-cache.at<3600000){posts=cache.posts;}else{const response=await fetch(feed,{headers:{'User-Agent':'ForgeRadar/0.2 public feed reader'},signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`Public Reddit feed returned HTTP ${response.status}`);const xml=await response.text();if(xml.length>2000000)throw new Error('Feed exceeds the size limit');posts=parseRedditFeed(xml);if(!posts.length)throw new Error('Public feed returned no readable entries');state.redditCache={at:Date.now(),posts,feed};}signals.push(...posts);sources.push({id:'reddit',name:'Reddit',status:'connected',count:posts.length,detail:'SomebodyMakeThis + AppIdeas + SideProject · public RSS, one-hour cache'});}catch(e){sources.push({id:'reddit',name:'Reddit',status:'error',count:0,detail:e.message+'; imports remain available.'});}
if(process.env.FORGERADAR_X_ENABLED==='1'&&process.env.X_BEARER_TOKEN){try{const query=encodeURIComponent('(software OR developer) ("wish" OR "frustrating" OR "need a tool") -is:retweet lang:en');const response=await fetch('https://api.x.com/2/tweets/search/recent?query='+query+'&max_results=10&tweet.fields=created_at,public_metrics',{headers:{Authorization:'Bearer '+process.env.X_BEARER_TOKEN},signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('X API returned HTTP '+response.status);const r=await response.json();const posts=(r.data||[]).map(s=>({id:'x-'+s.id,source:'X / Twitter',title:s.text.slice(0,180),description:s.text,url:'https://x.com/i/web/status/'+s.id,engagement:s.public_metrics?.like_count||0,collectedAt:new Date().toISOString()}));signals.push(...posts);sources.push({id:'x',name:'X / Twitter',status:'connected',count:posts.length,detail:'Authorized recent-search API'});}catch(e){sources.push({id:'x',name:'X / Twitter',status:'error',count:0,detail:e.message});}}else sources.push({id:'x',name:'X / Twitter',status:'needs_access',count:0,detail:'API token and explicit API enablement required; public-post imports available.'});
sources.push({id:'instagram',name:'Instagram',status:'import_only',count:(state.imports||[]).filter(s=>s.source==='Instagram').length,detail:'Public caption imports; automated Instagram discovery is not connected.'});
return {signals,sources};}
export function balancedEvidence(signals,limit=60){const groups=new Map();for(const signal of signals){const key=signal.imported?'Imported posts':signal.source;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(signal);}for(const group of groups.values())group.sort((a,b)=>(classifySignal(b)==='Idea request'?2:classifySignal(b)==='Problem signal'?1:0)-(classifySignal(a)==='Idea request'?2:classifySignal(a)==='Problem signal'?1:0));const result=[];let index=0;while(result.length<limit){let added=false;for(const group of groups.values()){if(group[index]){result.push(group[index]);added=true;if(result.length===limit)break;}}if(!added)break;index++;}return result.map(s=>({id:s.id,title:s.title.slice(0,180),description:(s.description||'').slice(0,700),signalType:classifySignal(s),source:s.source,url:s.url}));}
