import test from 'node:test';
import assert from 'node:assert/strict';
import {score,cluster,proposal,defaults} from './server.mjs';
import {createOrchestrator,validateMetrics,validateFiles,dailySlot,scopeError} from './orchestrator.mjs';
import {balancedEvidence,parseRedditFeed,classifySignal} from './social-sources.mjs';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
test('weighted ranking normalizes and follows career priority',()=>{assert.equal(score(Object.fromEntries(Object.keys(defaults).map(k=>[k,100]))),100);assert.equal(score({career:80,problem:20},{career:100,problem:0}),80);assert.equal(score({career:80,problem:20},{career:0,problem:100}),20);});
test('clustering keeps evidence and ignores unrelated signals',()=>{const result=cluster([{id:'a',title:'IAM security permissions',description:'',url:'https://example.com',source:'Test'},{id:'b',title:'Banana recipes',description:''}]);assert.equal(result.length,1);assert.equal(result[0].evidence[0].id,'a');assert.match(proposal(result[0]),/https:\/\/example.com/);assert.match(proposal(result[0]),/estimates/);});
test('invalid model scores and traversal filenames cannot pass validation',()=>{assert.throws(()=>validateMetrics({...Object.fromEntries(Object.keys(defaults).map(k=>[k,50])),career:101}));assert.throws(()=>validateFiles([{path:'../server.mjs',content:'bad'}]));assert.throws(()=>validateFiles([{path:'index.html',content:'<html><iframe></iframe>'},{path:'style.css',content:''},{path:'app.js',content:''}]));});
test('daily slot uses India time at the day boundary',()=>{assert.deepEqual(dailySlot(new Date('2026-10-03T15:29:59Z')),{day:'2026-10-03',due:false});assert.deepEqual(dailySlot(new Date('2026-10-03T15:30:00Z')),{day:'2026-10-03',due:true});assert.equal(dailySlot(new Date('2026-10-03T18:30:00Z')).day,'2026-10-04');});
test('evidence selection gives each community a turn and preserves imports',()=>{const signals=[...Array.from({length:30},(_,i)=>({id:'gh'+i,source:'GitHub',title:'Repo '+i})),{id:'reddit',source:'Reddit',title:'Community need'},{id:'ig',source:'Instagram',title:'Imported post',imported:true}];const selected=balancedEvidence(signals,6);assert(selected.some(s=>s.id==='reddit'));assert(selected.some(s=>s.id==='ig'));assert.equal(selected.length,6);});
test('public Reddit RSS yields text evidence without rendering markup',()=>{const xml='<feed><entry><id>t3_123</id><title>A &amp; B</title><link href="https://www.reddit.com/r/SideProject/comments/123/"/><content type="html">&lt;p&gt;Need a tool&lt;/p&gt;</content></entry></feed>';const result=parseRedditFeed(xml);assert.equal(result[0].title,'A & B');assert.equal(result[0].description,'Need a tool');assert.equal(result[0].source,'Reddit');});
async function fixture(modelAvailable=true){const temp=await mkdtemp(path.join(os.tmpdir(),'forgeradar-test-'));let synchronized=0;const state={signals:[{id:'hn-123',title:'Developers need a CSV validator',description:'CSV validation is difficult',source:'Hacker News',url:'https://example.com/evidence'}],opportunities:[],projects:[],weights:defaults,model:'test'};
const jsonFetch=async(url,options)=>{if(!url.includes('/api/chat'))return {items:[]};const request=JSON.parse(options.body);const role=request.messages[0].content.match(/Role: (\w+)/)[1];const input=JSON.parse(request.messages[1].content);let output;
if(role==='miner')output={opportunities:[{title:'CSV validation lab',problem:'CSV errors are hard to identify',users:'Data engineers',usecase:'Validate uploaded CSV',features:['Validate rows'],mvp:['Paste CSV and show invalid cells'],evidenceIds:['hn-123']}]};
if(role==='evaluator')output={metrics:Object.fromEntries(Object.keys(defaults).map(k=>[k,75])),rationale:'Practical learning and a clear user need',audienceFit:'Data engineers'};
if(role==='critic')output={critique:'Interview users; existing tools may already meet this need.',gapScore:60,noveltyScore:60};
if(role==='proposal')output={title:'CSV lab',summary:'Validate CSV locally',whyBest:'Best weighted candidate in this run',users:'Data engineers',mvp:['Validate CSV'],successCriteria:['A malformed row is identified'],risks:['Limited demand']};
if(role==='architect')output={name:'CSV lab prototype',summary:'Offline browser tool',tasks:['Build input','Show validation'],acceptance:['Invalid CSV reports a problem']};
if(role==='builder')output={summary:'Offline prototype generated',htmlBody:'<button id="run">Validate</button>',css:'body{font-family:sans-serif}',javascript:'document.querySelector("#run").addEventListener("click",()=>{});'};
return {message:{content:JSON.stringify(output)},prompt_eval_count:1,eval_count:1};};
const runtime=createOrchestrator({state,root:temp,persist:async()=>{},refresh:async()=>({warnings:[]}),models:async()=>({connected:modelAvailable,models:modelAvailable?['test']:[]}),jsonFetch,score,proposal,collectSocial:async()=>({signals:[],sources:[]}),synchronize:async p=>{synchronized++;return {projectId:p.id,status:'test sync'};}});
return {runtime,state,temp,get synchronized(){return synchronized;},async clean(){runtime.stop();const target=path.resolve(temp);if(!target.startsWith(path.resolve(os.tmpdir())+path.sep)||!path.basename(target).startsWith('forgeradar-test-'))throw new Error('Unsafe test cleanup');await rm(target,{recursive:true,force:true});}};}
test('roles hand off validated artifacts and publish only after QA',async()=>{const f=await fixture();try{await f.runtime.start('discover');assert.equal(f.state.machine.status,'complete');assert.equal(f.synchronized,1);assert.deepEqual(f.state.handoffs.map(h=>h.from).reverse(),['scout','miner','evaluator','critic','proposal','architect','builder','qa']);assert.equal(f.state.agentStates.qa.output.syntax,'Passed');assert.equal(f.state.projects[0].iterations,1);assert.match(await readFile(path.join(f.temp,'projects',f.state.projects[0].id,'README.md'),'utf8'),/offline browser prototype/);}finally{await f.clean();}});
test('an offline model stops the miner and never calls builder or sync',async()=>{const f=await fixture(false);try{await f.runtime.start('discover');assert.equal(f.state.machine.status,'blocked');assert.equal(f.state.agentStates.scout.status,'complete');assert.equal(f.state.agentStates.miner.status,'blocked');assert.equal(f.state.agentStates.builder.status,'idle');assert.equal(f.synchronized,0);assert.equal(f.state.projects.length,0);}finally{await f.clean();}});

test('unbuilt community ideas are retained ahead of generic discussion',()=>{const idea={id:'idea',source:'Reddit',title:'An idea for a tool that does not exist yet'};assert.equal(classifySignal(idea),'Idea request');assert.equal(balancedEvidence([{id:'discussion',source:'Reddit',title:'Launch news'},idea],1)[0].id,'idea');});

test('scope gate distinguishes restrictions from integration requirements',()=>{assert.equal(scopeError(['No API calls; without localStorage']),null);assert.match(scopeError(['Integrate with a live API']),/Unsupported/);assert.match(scopeError(['Use localStorage persistence']),/Unsupported/);});
